name: dashhost_flutter
description: "Dashhost Flutter provides components for generating SEO in flutter web apps"
version: 0.0.5
homepage: https://dashhost.app
repository: https://github.com/Dashhost/dashhost-flutter

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
